# Site settings
title:          nnh Glukk Inc.
description:    Разработка qLua скриптов
url:            https://github.com/nick-nh/
avatar:         /assets/title.png

# Author
author:
  name:         Nikolay Hartanovic
  email:        nick-h@yandex.ru
  url:          https://nick-nh.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

navigation:
 - title: About
   url: /about

# Links to social media
social:
  email: nick-h@yandex.ru
  github: https://github.com/nick-nh/qlua
  twitter: https://twitter.com/niknh
  youtube: https://www.youtube.com/channel/UCKLHojn_B8Zs5GrkGWzmwJQ
